stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - kushhhh_tag      # <-- change to your runner's tag
  script:
    - cd Backend/ComS309Tables        # Ensure the path is correct
    - mvn package
  only:
    refs:
      - Kush_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - kushhhh_tag     # <-- change to your runner's tag
  script:
    - cd Backend/ComS309Tables       # Ensure the path is correct
    - mvn test
  only:
    refs:
      - Kush_CICD
    changes:
      - Backend/**/*
